"""add artists and track_artists tables

Revision ID: f6ce60d2e280
Revises: 
Create Date: 2026-09-04 19:55:36.202347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6ce60d2e280'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks_artists',
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    op.alter_column('auth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listening_history', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uix_track_played_at'), 'listening_history', type_='unique')
    op.create_unique_constraint('uix_track_played_at', 'listening_history', ['user_id', 'track_id', 'played_at'])
    op.alter_column('simple_songs', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracks', 'album',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracks', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracks', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tracks', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tracks', 'popularity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tracks', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tracks', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tracks', 'album',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('simple_songs', 'spotify_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uix_track_played_at', 'listening_history', type_='unique')
    op.create_unique_constraint(op.f('uix_track_played_at'), 'listening_history', ['track_id', 'played_at'], postgresql_nulls_not_distinct=False)
    op.alter_column('listening_history', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('tracks_artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
